language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: true
node_js:
  - '6'
script:
  - ./next-update-travis.sh
  - npm run demo
  # run test only if node 6?
  - npm test
before_script:
  - npm prune
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
