language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: true
node_js:
  - '4'
  - '6'
script:
  - npm run demo
  - ./next-update-travis.sh
  - $(npm bin)/if-node-version ">=6" npm test
before_script:
  - npm prune
after_success:
  - TRAVIS_JOB_NUMBER=WORKAROUND.1 $(npm bin)/if-node-version ">=6" npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
